version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-druid
          RAILS_ENV: test
          MESSAGE_DELIVERY_REPLY_TO: messages@example.com
          MESSAGE_DELIVERY_TWILIO_PHONE: "+5555555555"
          MESSAGE_WHITELIST_ENABLED: false
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-druid
          POSTGRES_DB: bluesky-web_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - druid-bundle-v2-{{ checksum "Gemfile.lock" }}
            - druid-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --path vendor/bundle
      - save_cache:
          key: druid-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - restore_cache:
          keys:
            - druid-yarn-{{ checksum "yarn.lock" }}
            - druid-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: druid-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run Rspec
          command: |
            mkdir -p ./tmp/test_results && \
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: ./tmp/test_results
      - store_artifacts:
          path: ./tmp/test_results
          destination: test-results
